app.name=side-car

logfile=false
runtime.mode=local

server.host=0.0.0.0
server.port=8899

sidecar.peers=
sidecar.discovery.label=a-haythorus.io/enabled=true

pod.name=local-dev
pod.namespace=default
pod.node=localhost
pod.app=demo-app

collector.interval.ms=5000

cluster.connect.timeout.ms=1000
cluster.request.timeout.ms=2000